name: python-build
description: Build a wheel, re-using the python-setup action

inputs:
  python-version:
    description: Python version to use
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    - uses: ./.github/actions/python-setup
      with:
        python-version: ${{ inputs.python-version }}

    - name: Build wheel
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build --wheel
