on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  build:
    # only run if the tests.yml workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install .[dev]
      - run: python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
