name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        type: choice
        options: [major, minor, patch]
        default: patch

permissions: 
    contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  bump:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4

      - name: Bump, commit, tag & push
        uses: callowayproject/bump-my-version@1.2.0
        with:
          args: >-
            ${{ inputs.bump-type }} --commit --tag --push
