name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: ./.github/actions/python-setup
        with:
          python-version: 3.12

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
