name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/python-ci.yml
    with:
      python-versions: '["3.12"]'
      test-command: 'pytest'

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install docs dependencies
        run: |
          pip install .[docs]

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
